name : Deploy to Google Cloud

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH into Google Cloud instance
        uses: appleboy/ssh-action@master
        with:
          host: 34.131.64.204
          username: nikhilkotiya8
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su
            cd /home/chooserightai/Homepage
            sudo git pull origin main &&
            sudo rm -r node_modules/
            sudo rm -r build/
            sudo npm install
            sudo  npm run build &&
            cd .. &&
            sudo cp -r ./Homepage/build/* /var/www/html/ &&
            sudo service apache2 restart
